Added NPQ test functions
callumrollo/glidertest pull request #12
Opened 2024-06-27 13:42 UTC by MOchiara

2024-06-27 13:46 UTC, MOchiara commented
@callumrollo

2024-06-27 14:03 UTC, callumrollo requested changes

2024-06-27 14:03 UTC, callumrollo commented on glidertest/tools.py
> +    ds = ds.set_xindex('TIME')
docstring here too please

2024-06-27 14:03 UTC, callumrollo commented on notebooks/demo.ipynb
>     "cell_type": "code",
please add a markdown cell here explaining what this does

2024-06-27 14:15 UTC, MOchiara commented on glidertest/tools.py
> +    date = grp_avg.index
this is all glider tools and I haven't modified it ahah

2024-06-27 14:17 UTC, callumrollo commented on glidertest/tools.py
> +    date = grp_avg.index
then whoever wrote it should feel bad! Also you should reference in the docstring if it's a function copied from somewhere else

2024-06-27 14:18 UTC, MOchiara commented on glidertest/tools.py
> +def sunset_sunrise(time, lat, lon):
I will add it, we can later doc strings to all the functions once we say we like them

2024-07-01 06:07 UTC, callumrollo requested changes
Looking good! One final change: rename the function `test_npq` to something else. You only name a function starting with `test_` if it is a software test

2024-07-01 06:50 UTC, MOchiara commented
Very true with the function starting with test, my bad. Changed now

2024-07-01 06:54 UTC, callumrollo approved these changes

2024-07-01 06:54 UTC, merged