[FEAT] Added checks and plots based on oxygen SOP
callumrollo/glidertest pull request #139
Opened 2024-11-26 14:37 UTC by MOchiara

2024-11-27 07:57 UTC, MOchiara commented
Currently the spike function is the least efficient thing ever produced so any suggestions are more than welcome

2024-11-27 08:09 UTC, callumrollo commented
I think this might be a case where it is best to use existing libraries rather than reinventing the wheel. In this case, I would recommend looking at [ioos_qc](https://github.com/ioos/ioos_qc) which implements the QARTOD toolbox including global range, spike test and stuck values.

I wrote an example notebook with some glider data for it https://github.com/ioos/ioos_qc/blob/main/docs/source/examples/QartodTestExample_Glider.ipynb

2024-11-27 08:32 UTC, MOchiara commented
Uhh fair point! I will check it now and implement it, thanks for the suggestion!

2024-11-27 08:34 UTC, callumrollo commented
It might be something to discuss with later today, OG1 support a standardised approach to QC, so we could have a function called pretty early on that runs QC on the whole dataset, then we can just pass that dataset with QC vars to various plotting functions

2024-11-28 10:45 UTC, MOchiara commented
<img width="494" alt="image" src="https://github.com/user-attachments/assets/5b166af4-6a17-452d-b206-5ecff9e33e2b">

2024-11-28 10:55 UTC, callumrollo requested changes

2024-11-28 10:55 UTC, callumrollo commented on requirements.txt
>  cartopy
ioos_qc should be in here too I think?

2024-11-28 10:55 UTC, callumrollo commented on tests/test_plots.py
> +import ioos_qc.qartod as ioos_qc
this is a very confusing way to do an import. How about `from ioos_qc import qartod` ?

2024-11-28 11:05 UTC, callumrollo approved these changes

2024-11-28 11:08 UTC, merged