[FEAT] Add package description to index.rst
callumrollo/glidertest pull request #81
Opened 2024-11-06 13:18 UTC by MOchiara

2024-11-06 13:19 UTC, MOchiara commented
This is a draft! Give inputs, it's ugly now I know!

2024-11-06 13:20 UTC, MOchiara commented
#78

2024-11-08 10:59 UTC, callumrollo commented on docs/source/index.rst
> +Glidertest is a Python package aiming to diagnose possible issues with your glider dataset. The package takes as input data from any glider in OG1 format.
How about some links like this ` OG1 format <https://github.com/OceanGlidersCommunity/OG-format-user-manual>`_

2024-11-08 11:00 UTC, callumrollo commented on docs/source/index.rst
> +    * Bennett (2013)
Get full citations to these papers!

2024-11-08 11:01 UTC, callumrollo commented on docs/source/index.rst
> +We provide an example demo to demonstrate the purpose of the various function and test datasets from SeaExplorer data in the Baltic and Seaglider data in the Labrador Sea.
"example notebook" maybe? example demo sounds odd

2024-11-08 11:01 UTC, callumrollo requested changes
Great additions! I've made a couple of suggestions

2024-11-11 08:35 UTC, callumrollo approved these changes

2024-11-11 08:37 UTC, merged